config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # made home the root directory
  root 'pages#home'

  # unnecessary since it's now the root
  get 'pages/home'

  # about path automatically picks controller action
  get 'pages/about'

  # about path, linked with controller action, doesn't show controller name :)
  get 'about', to: 'pages#about'

  # creates routes for edit, delete, post, get, put and patch article
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources(:categories, except: [:destroy])
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show update destroy]
  before_action :require_user, except: [:index, :show]
  # before_action :require_same_user, only: [:edit, :update, :destroy]

  before_action only: [:edit, :update, :destroy] do
    require_same_user(@article.user, 'You can only edit or delete your own article')
  end

  def new
    @article = Article.new
  end

  def create
    # debugger
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to articles_path(@article)
    else
      render 'new'
    end
  end

  def show
    # @article = Article.find(params[:id])
  end

  def edit
    # @article = Article.find(params[:id])
    # changed to a before_action require_same_user
    # redirect_to articles_path unless current_user.eql? @article.user
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def index
    # Using paginate instead of .all to create pages
    # @articles = Article.all
    # @articles = Article.paginate(page: params[:page]) # default is 30, limiting it to 5
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  # def require_same_user
  #   unless current_user.eql? @article.user
  #     flash[:danger] = 'You can only edit or delete your own article'
  #     redirect_to user_path(current_user)
  #   end
  # end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="article-body">
            <%= truncate(article.description, length: 100, seperator: ' ') %> <br>
            <div class="article-meta-details">
              <small>Created by: <%= article.user.username if article.user %> <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago.</small>
            </div>
          </div>

          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>

          <% if logged_in? && (current_user.eql?(article.user) or current_user.admin?) %>
            <div class="article-actions" align="center">
              <%= link_to 'Edit this article', edit_article_path(article), class: 'btn btn-xs btn-primary' %>
              <%= link_to 'Delete this article', article_path(article), method: :delete, data: {confirm: 'Are you sure you want to delete the article?'}, class: 'btn btn-xs btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-sm-12">

    <%= form_for(@article, html: { class: 'form-horizontal', role: 'form' } ) do |form| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= form.label :title %>
          </div>
          <div class="col-sm-8">
            <%= form.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= form.label :description %>
          </div>
          <div class="col-sm-8">
            <%= form.text_area :description, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
              <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |checkBox| %>
                <% checkBox.label(class: 'checkbox-inline input_checkbox') { checkBox.check_box(class: 'checkbox') + checkBox.text } %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= form.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
    <% end %>

    <div class="text-center">
      [ <%= link_to 'Cancel request and return to articles list', articles_path %> ]
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">All articles</h1>

<%= render('shared/paginate', obj: @articles) %>

<%= render('article', obj: @articles) %>

<%= render('shared/paginate', obj: @articles) %>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center">Title: <%= @article.title %></h2>
<div class="row">
  <div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <ul class="listing text-center">
            <li>Created by:</li>
            <li><%= link_to(gravatar_for(@article.user), user_path(@article.user)) %></li>
            <li class="article-title"><%= link_to(@article.user.username, user_path(@article.user)) %></li>
            <li><small><%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %></small></li>
          </ul>
        </div>
      </div>
    <% end %>
    <h4 class="text-center"><strong>Description:</strong></h4>
    <hr>
    <p> <%= simple_format(@article.description) %></p>


    <%# if @article.categories.any? %>
      <!--<p>Categories:-->
        <%# @article.categories.each do |category| %>
          <!--<span class="badge"><%= link_to "#{category.name}", category_path(category) %></span>-->
        <%# end %>
      <!--</p>-->
    <%# end %>

    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>

    <div class="article-actions" align="center">
      <%= link_to 'View all articles', articles_path, class: 'btn btn-xs btn-success' %>
      <% if logged_in? && current_user.eql?(@article.user) or current_user.admin? %>
        <%= link_to 'Edit this article', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
        <%= link_to 'Delete this article', article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to delete the article?'}, class: 'btn btn-xs btn-danger' %>
      <% end %>
    </div>
  </div>
</div>