config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # made home the root directory
  root 'pages#home'

  # unnecessary since it's now the root
  get 'pages/home'

  # about path automatically picks controller action
  get 'pages/about'

  # about path, linked with controller action, doesn't show controller name :)
  get 'about', to: 'pages#about'

  # creates routes for edit, delete, post, get, put and patch article
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources(:categories, except: [:destroy])
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category was created successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category was successfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    # if !logged_in? || (logged_in? && !current_user.admin?)
    unless logged_in? && current_user.admin?
      flash[:danger] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>&nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_for(@category, html: { class: 'form-horizontal', role: 'form' } ) do |form| %>
    <div class="form-group">
      <div class="control-label col-sm-2 col-sm-offset-2">
        <%= form.label :name %>
      </div>
      <div class="col-sm-4">
        <%= form.text_field :name, class: 'form-control', placeholder: 'Category name', autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= form.submit(class: 'btn btn-primary btn-lg') %>
      </div>
    </div>
<% end %>

<div class="text-center">
  [ <%= link_to 'Cancel request and return to articles list', articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category "<%= "#{@category.name}" %>"</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">Listing All Categories</h1>

<div class="text-center">
  <%= will_paginate %>
  <%# @categories.each do |category| %>
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <% @categories.each do |category| %>
        <ul class="listing">
          <li class="article-title"><%= link_to "#{category.name}", category_path(category) %></li>
          <li><small><%= pluralize(category.articles.count, 'article') %></small></li>
        </ul>
      <% end %>
    </div>
  </div>
  <%# end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center"><%= "Category: #{@category.name}" %></h1>

<% if logged_in? && current_user.admin? %>
  <p class="text-center"><span class="badge"><%= link_to 'Edit Category Name', edit_category_path(@category) %></span></p>
<% end %>

<%= render('shared/paginate', obj: @category_articles) %>

<%= render('articles/article', obj: @category_articles) %>

<%= render('shared/paginate', obj: @category_articles) %>