config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # made home the root directory
  root 'pages#home'

  # unnecessary since it's now the root
  get 'pages/home'

  # about path automatically picks controller action
  get 'pages/about'

  # about path, linked with controller action, doesn't show controller name :)
  get 'about', to: 'pages#about'

  # creates routes for edit, delete, post, get, put and patch article
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources(:categories, except: [:destroy])
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Copyright &copy; <%= Time.now.year %> <%= link_to 'Esirei', 'https://esirei.com' %>.</small>
  <nav>
    <ul>
      <!--Block to enter ruby code, the equal sign renders what is evaluated in it-->
      <li><%= link_to 'About', about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= "#{name}" %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href=<%= root_path %>>TheRailsFramework</a>-->
      <%= link_to 'TheRailsFramework', root_path, class: 'navbar-brand', id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span> </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Article', new_article_path %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span> </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
                <li><%= link_to 'Add new Category', new_category_path %></li>
                <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to 'All Categories', categories_path %></li>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<%= ' (Admin)' if current_user.admin? %><span class="caret"></span> </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View your profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
            </ul>
          </li>
          <li><%= link_to 'About Me', about_path %></li>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to('Log in', login_path) %></li>
          <li><%= link_to('Sign up', signup_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheRailsFramework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  <%= debug params if Rails.env.development? %>
  </body>
</html>